In [6]:
import numpy as np

#shape of array
#axis 0 is the rows
#axis 1 is the columns
#axis 2 is the width

#checking the shape of an array
x = np.array([ [67, 63, 87],
[77, 69, 59],
[85, 87, 99],
[79, 72, 71],
[63, 89, 93],
[68, 92, 78]])

print(np.shape(x))

#changing the shape
x.shape=(9,2)
print(x)


#representing a multidimension array
x=np.array([[[2,4,6],[1,2,3]],[[3,6,9],[6,12,18]],[[4,8,12],[8,16,24]]])

print(np.shape(x))

#changing the shape
x.shape=(3,3,2)
print(x)

(6, 3)
[[67 63]
 [87 77]
 [69 59]
 [85 87]
 [99 79]
 [72 71]
 [63 89]
 [93 68]
 [92 78]]
(3, 2, 3)
[[[ 2  4]
  [ 6  1]
  [ 2  3]]

 [[ 3  6]
  [ 9  6]
  [12 18]]

 [[ 4  8]
  [12  8]
  [16 24]]]


In [ ]:
import numpy as np

#indexing and slicing

#the syntax for one dimension is 
'''  A[start:stop:step]  '''

